#!/usr/bin/env bash
# generate-data.sh - Generate site/data.js from fixture READMEs using hdi --json
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
HDI="$ROOT/hdi"
OUT="$SCRIPT_DIR/data.js"

# Project metadata: slug|name|description|lang|langFull
projects=(
  "node-express|express-api|Invoice management REST API|JS|JavaScript"
  "python-flask|flask-app|Sensor data processing service|PY|Python"
  "ruby-rails|rails-app|Team project management app|RB|Ruby"
  "react-nextjs|my-next-app|SaaS analytics dashboard|TS|TypeScript"
  "go-project|go-service|Event stream microservice|GO|Go"
)

# Extract VERSION from hdi
VERSION=$("$HDI" --version | awk '{print $2}')

# Start output
{
  printf '// Auto-generated by site/generate-data.sh — do not edit manually\n\n'
  printf 'const PROJECTS = [\n'

  first_project=true
  for entry in "${projects[@]}"; do
    IFS='|' read -r slug name description lang langFull <<< "$entry"
    readme_file="$ROOT/test/fixtures/$slug/README.md"

    if [[ ! -f "$readme_file" ]]; then
      echo "ERROR: Missing fixture: $readme_file" >&2
      exit 1
    fi

    $first_project || printf ',\n'
    first_project=false

    # Get hdi --json output
    json=$("$HDI" --json "$readme_file" 2>/dev/null)

    # Read README content, escape for JS template literal
    readme_content=$(< "$readme_file")
    readme_escaped="${readme_content//\\/\\\\}"
    readme_escaped="${readme_escaped//\`/\\\`}"
    readme_escaped="${readme_escaped//\$/\\\$}"

    # Extract modes, fullProse, check from JSON
    modes=$(printf '%s' "$json" | python3 -c "
import json, sys
d = json.load(sys.stdin)

def fmt_item(item, indent=6):
    parts = []
    for k, v in item.items():
        if isinstance(v, bool):
            parts.append(f'{k}: {\"true\" if v else \"false\"}')
        elif isinstance(v, str):
            parts.append(f'{k}: {json.dumps(v)}')
        else:
            parts.append(f'{k}: {v}')
    return ' ' * indent + '{ ' + ', '.join(parts) + ' }'

def print_array(items, indent=6):
    for i, item in enumerate(items):
        trail = ',' if i < len(items) - 1 else ','
        print(fmt_item(item, indent) + trail)

# modes
print('    modes: {')
for mode, items in d['modes'].items():
    if items:
        print(f'      {mode}: [')
        print_array(items, 8)
        print(f'      ],')
    else:
        print(f'      {mode}: [],')
print('    },')

# check
print('    check: [')
print_array(d['check'], 6)
print('    ],')

# fullProse
print('    fullProse: {')
for mode, items in d['fullProse'].items():
    if items:
        print(f'      {mode}: [')
        print_array(items, 8)
        print(f'      ],')
    else:
        print(f'      {mode}: [],')
print('    },')
")

    printf '  {\n'
    printf '    slug: %s,\n' "\"$slug\""
    printf '    name: %s,\n' "\"$name\""
    printf '    description: %s,\n' "\"$description\""
    printf '    lang: %s,\n' "\"$lang\""
    printf '    langFull: %s,\n' "\"$langFull\""
    printf '    readme: `%s`,\n' "$readme_escaped"
    printf '%s\n' "$modes"
    printf '  }'
  done

  printf '\n];\n\n'

  # HELP_TEXT from hdi --help
  help=$("$HDI" --help 2>/dev/null || true)
  help_escaped="${help//\\/\\\\}"
  help_escaped="${help_escaped//\`/\\\`}"
  help_escaped="${help_escaped//\$/\\\$}"
  printf 'const HELP_TEXT = `%s`;\n\n' "$help_escaped"

  printf 'const VERSION = "%s";\n' "$VERSION"
} > "$OUT"

echo "Generated: $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
